linters:
  checkstyle:
    config: ./checkstyle.xml
    fixer: true
  eslint:
    config: './.eslintrc'
    fixer: true
  csslint: {  }
files:
  ignore:
    - 'bower_components/*'
    - 'node_modules/*'

